package framework.sql;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import framework.sql.SearchSuffix;

import framework.sql.SearchSuffixDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchSuffixDaoConfig;

    private final SearchSuffixDao searchSuffixDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchSuffixDaoConfig = daoConfigMap.get(SearchSuffixDao.class).clone();
        searchSuffixDaoConfig.initIdentityScope(type);

        searchSuffixDao = new SearchSuffixDao(searchSuffixDaoConfig, this);

        registerDao(SearchSuffix.class, searchSuffixDao);
    }
    
    public void clear() {
        searchSuffixDaoConfig.getIdentityScope().clear();
    }

    public SearchSuffixDao getSearchSuffixDao() {
        return searchSuffixDao;
    }

}
