package develop.y.zhzl;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SEARCH_SUFFIX".
 */
public class SearchSuffix {

    private Integer id;
    private String suffix;

    public SearchSuffix() {
    }

    public SearchSuffix(Integer id) {
        this.id = id;
    }

    public SearchSuffix(Integer id, String suffix) {
        this.id = id;
        this.suffix = suffix;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSuffix() {
        return suffix;
    }

    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

}
